# Site settings
title: Lydelln.github.io
email: llnewby3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Lydell, I'm actively learning about the computer sciences and have strong interest in Web and Software development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lydelln.github.io" # the base hostname & protocol for your site
twitter_username: dangerous_l
github_username:  lydelln

# Build settings
markdown: kramdown
